### ISSUE TITLE
Can't able to apply.

### ISSUE THREAD

**Issue by Aadilhassan** [GitHub-Campus-IITM/10-days-of-code#1]
![Screenshot_2021-12-16-08-30-31-867_com android chrome](https://user-images.githubusercontent.com/68943818/146300360-8e840053-82da-4dde-a6eb-8dd889d6a0ee.jpg)

**Comment by sudip-mondal-2002** [comment]
mentors application not open for students outside iitm except for our partner organizations, if you're from iitm, use smail
