### ISSUE TITLE
Is application for participatents closed?

### ISSUE THREAD

**Issue by arnav-kr** [GitHub-Campus-IITM/10-days-of-code#2]

**Comment by sujoy-coder** [comment]
Same doubt. How can I apply as a participant ?

**Comment by abdulragib** [comment]
same doubt, because when I click on participants it is showing me it is only for organisation member's

**Comment by rishitajain01** [comment]
+1

**Comment by arnav-kr** [comment]
> same doubt, because when I click on participants it is showing me it is only for organisation member's

maybe you had clicked on mentor registration links.
as only people at IITM can take part as mentors

**Comment by rishitajain01** [comment]
Where I have to register for 10 days of code?

**Comment by arnav-kr** [comment]
Hey Guys, according to their poster i think its already ended

![poster](https://raw.githubusercontent.com/GitHub-Campus-IITM/10-days-of-code/main/Posters/10-days-of-code.jpeg)

application gor participants already closed on 11/12/2021
it already begun on 21/12/2021

and in two days project will be submitted so ig we can't participate

so i am closing the issue
